const MAX_32_BITS = 4294967295;
const MAX_16_BITS = 65535;
const MAX_8_BITS = 255;
const COMPRESSION_METHOD_DEFLATE = 8;
const COMPRESSION_METHOD_DEFLATE_64 = 9;
const COMPRESSION_METHOD_STORE = 0;
const COMPRESSION_METHOD_AES = 99;
const LOCAL_FILE_HEADER_SIGNATURE = 67324752;
const SPLIT_ZIP_FILE_SIGNATURE = 134695760;
const DATA_DESCRIPTOR_RECORD_SIGNATURE = SPLIT_ZIP_FILE_SIGNATURE;
const CENTRAL_FILE_HEADER_SIGNATURE = 33639248;
const END_OF_CENTRAL_DIR_SIGNATURE = 101010256;
const ZIP64_END_OF_CENTRAL_DIR_SIGNATURE = 101075792;
const ZIP64_END_OF_CENTRAL_DIR_LOCATOR_SIGNATURE = 117853008;
const END_OF_CENTRAL_DIR_LENGTH = 22;
const ZIP64_END_OF_CENTRAL_DIR_LOCATOR_LENGTH = 20;
const ZIP64_END_OF_CENTRAL_DIR_LENGTH = 56;
const ZIP64_END_OF_CENTRAL_DIR_TOTAL_LENGTH = END_OF_CENTRAL_DIR_LENGTH + ZIP64_END_OF_CENTRAL_DIR_LOCATOR_LENGTH + ZIP64_END_OF_CENTRAL_DIR_LENGTH;
const DATA_DESCRIPTOR_RECORD_LENGTH = 12;
const DATA_DESCRIPTOR_RECORD_ZIP_64_LENGTH = 20;
const DATA_DESCRIPTOR_RECORD_SIGNATURE_LENGTH = 4;
const EXTRAFIELD_TYPE_ZIP64 = 1;
const EXTRAFIELD_TYPE_AES = 39169;
const EXTRAFIELD_TYPE_NTFS = 10;
const EXTRAFIELD_TYPE_NTFS_TAG1 = 1;
const EXTRAFIELD_TYPE_EXTENDED_TIMESTAMP = 21589;
const EXTRAFIELD_TYPE_UNICODE_PATH = 28789;
const EXTRAFIELD_TYPE_UNICODE_COMMENT = 25461;
const EXTRAFIELD_TYPE_USDZ = 6534;
const EXTRAFIELD_TYPE_INFOZIP = 30837;
const EXTRAFIELD_TYPE_UNIX = 30805;
const BITFLAG_ENCRYPTED = 1;
const BITFLAG_LEVEL = 6;
const BITFLAG_LEVEL_MAX_MASK = 2;
const BITFLAG_LEVEL_FAST_MASK = 4;
const BITFLAG_LEVEL_SUPER_FAST_MASK = 6;
const BITFLAG_DATA_DESCRIPTOR = 8;
const BITFLAG_LANG_ENCODING_FLAG = 2048;
const FILE_ATTR_MSDOS_DIR_MASK = 16;
const FILE_ATTR_MSDOS_READONLY_MASK = 1;
const FILE_ATTR_MSDOS_HIDDEN_MASK = 2;
const FILE_ATTR_MSDOS_SYSTEM_MASK = 4;
const FILE_ATTR_MSDOS_ARCHIVE_MASK = 32;
const FILE_ATTR_UNIX_TYPE_MASK = 61440;
const FILE_ATTR_UNIX_TYPE_DIR = 16384;
const FILE_ATTR_UNIX_EXECUTABLE_MASK = 73;
const FILE_ATTR_UNIX_DEFAULT_MASK = 420;
const FILE_ATTR_UNIX_SETUID_MASK = 2048;
const FILE_ATTR_UNIX_SETGID_MASK = 1024;
const FILE_ATTR_UNIX_STICKY_MASK = 512;
const VERSION_DEFLATE = 20;
const VERSION_ZIP64 = 45;
const VERSION_AES = 51;
const DIRECTORY_SIGNATURE = "/";
const HEADER_SIZE = 30;
const HEADER_OFFSET_SIGNATURE = 10;
const HEADER_OFFSET_COMPRESSED_SIZE = 14;
const HEADER_OFFSET_UNCOMPRESSED_SIZE = 18;
const MAX_DATE = new Date(2107, 11, 31);
const MIN_DATE = new Date(1980, 0, 1);
const UNDEFINED_VALUE = void 0;
const INFINITY_VALUE = Infinity;
const UNDEFINED_TYPE = "undefined";
const FUNCTION_TYPE = "function";
const OBJECT_TYPE = "object";
export {
  BITFLAG_DATA_DESCRIPTOR,
  BITFLAG_ENCRYPTED,
  BITFLAG_LANG_ENCODING_FLAG,
  BITFLAG_LEVEL,
  BITFLAG_LEVEL_FAST_MASK,
  BITFLAG_LEVEL_MAX_MASK,
  BITFLAG_LEVEL_SUPER_FAST_MASK,
  CENTRAL_FILE_HEADER_SIGNATURE,
  COMPRESSION_METHOD_AES,
  COMPRESSION_METHOD_DEFLATE,
  COMPRESSION_METHOD_DEFLATE_64,
  COMPRESSION_METHOD_STORE,
  DATA_DESCRIPTOR_RECORD_LENGTH,
  DATA_DESCRIPTOR_RECORD_SIGNATURE,
  DATA_DESCRIPTOR_RECORD_SIGNATURE_LENGTH,
  DATA_DESCRIPTOR_RECORD_ZIP_64_LENGTH,
  DIRECTORY_SIGNATURE,
  END_OF_CENTRAL_DIR_LENGTH,
  END_OF_CENTRAL_DIR_SIGNATURE,
  EXTRAFIELD_TYPE_AES,
  EXTRAFIELD_TYPE_EXTENDED_TIMESTAMP,
  EXTRAFIELD_TYPE_INFOZIP,
  EXTRAFIELD_TYPE_NTFS,
  EXTRAFIELD_TYPE_NTFS_TAG1,
  EXTRAFIELD_TYPE_UNICODE_COMMENT,
  EXTRAFIELD_TYPE_UNICODE_PATH,
  EXTRAFIELD_TYPE_UNIX,
  EXTRAFIELD_TYPE_USDZ,
  EXTRAFIELD_TYPE_ZIP64,
  FILE_ATTR_MSDOS_ARCHIVE_MASK,
  FILE_ATTR_MSDOS_DIR_MASK,
  FILE_ATTR_MSDOS_HIDDEN_MASK,
  FILE_ATTR_MSDOS_READONLY_MASK,
  FILE_ATTR_MSDOS_SYSTEM_MASK,
  FILE_ATTR_UNIX_DEFAULT_MASK,
  FILE_ATTR_UNIX_EXECUTABLE_MASK,
  FILE_ATTR_UNIX_SETGID_MASK,
  FILE_ATTR_UNIX_SETUID_MASK,
  FILE_ATTR_UNIX_STICKY_MASK,
  FILE_ATTR_UNIX_TYPE_DIR,
  FILE_ATTR_UNIX_TYPE_MASK,
  FUNCTION_TYPE,
  HEADER_OFFSET_COMPRESSED_SIZE,
  HEADER_OFFSET_SIGNATURE,
  HEADER_OFFSET_UNCOMPRESSED_SIZE,
  HEADER_SIZE,
  INFINITY_VALUE,
  LOCAL_FILE_HEADER_SIGNATURE,
  MAX_16_BITS,
  MAX_32_BITS,
  MAX_8_BITS,
  MAX_DATE,
  MIN_DATE,
  OBJECT_TYPE,
  SPLIT_ZIP_FILE_SIGNATURE,
  UNDEFINED_TYPE,
  UNDEFINED_VALUE,
  VERSION_AES,
  VERSION_DEFLATE,
  VERSION_ZIP64,
  ZIP64_END_OF_CENTRAL_DIR_LENGTH,
  ZIP64_END_OF_CENTRAL_DIR_LOCATOR_LENGTH,
  ZIP64_END_OF_CENTRAL_DIR_LOCATOR_SIGNATURE,
  ZIP64_END_OF_CENTRAL_DIR_SIGNATURE,
  ZIP64_END_OF_CENTRAL_DIR_TOTAL_LENGTH
};
