const OPTION_FILENAME_ENCODING = "filenameEncoding";
const OPTION_COMMENT_ENCODING = "commentEncoding";
const OPTION_DECODE_TEXT = "decodeText";
const OPTION_EXTRACT_PREPENDED_DATA = "extractPrependedData";
const OPTION_EXTRACT_APPENDED_DATA = "extractAppendedData";
const OPTION_PASSWORD = "password";
const OPTION_RAW_PASSWORD = "rawPassword";
const OPTION_PASS_THROUGH = "passThrough";
const OPTION_SIGNAL = "signal";
const OPTION_CHECK_PASSWORD_ONLY = "checkPasswordOnly";
const OPTION_CHECK_OVERLAPPING_ENTRY_ONLY = "checkOverlappingEntryOnly";
const OPTION_CHECK_OVERLAPPING_ENTRY = "checkOverlappingEntry";
const OPTION_CHECK_SIGNATURE = "checkSignature";
const OPTION_TRANSFER_STREAMS = "transferStreams";
const OPTION_PREVENT_CLOSE = "preventClose";
const OPTION_ENCRYPTION_STRENGTH = "encryptionStrength";
const OPTION_EXTENDED_TIMESTAMP = "extendedTimestamp";
const OPTION_KEEP_ORDER = "keepOrder";
const OPTION_LEVEL = "level";
const OPTION_BUFFERED_WRITE = "bufferedWrite";
const OPTION_CREATE_TEMP_STREAM = "createTempStream";
const OPTION_DATA_DESCRIPTOR_SIGNATURE = "dataDescriptorSignature";
const OPTION_USE_UNICODE_FILE_NAMES = "useUnicodeFileNames";
const OPTION_DATA_DESCRIPTOR = "dataDescriptor";
const OPTION_SUPPORT_ZIP64_SPLIT_FILE = "supportZip64SplitFile";
const OPTION_ENCODE_TEXT = "encodeText";
const OPTION_OFFSET = "offset";
const OPTION_USDZ = "usdz";
const OPTION_UNIX_EXTRA_FIELD_TYPE = "unixExtraFieldType";
export {
  OPTION_BUFFERED_WRITE,
  OPTION_CHECK_OVERLAPPING_ENTRY,
  OPTION_CHECK_OVERLAPPING_ENTRY_ONLY,
  OPTION_CHECK_PASSWORD_ONLY,
  OPTION_CHECK_SIGNATURE,
  OPTION_COMMENT_ENCODING,
  OPTION_CREATE_TEMP_STREAM,
  OPTION_DATA_DESCRIPTOR,
  OPTION_DATA_DESCRIPTOR_SIGNATURE,
  OPTION_DECODE_TEXT,
  OPTION_ENCODE_TEXT,
  OPTION_ENCRYPTION_STRENGTH,
  OPTION_EXTENDED_TIMESTAMP,
  OPTION_EXTRACT_APPENDED_DATA,
  OPTION_EXTRACT_PREPENDED_DATA,
  OPTION_FILENAME_ENCODING,
  OPTION_KEEP_ORDER,
  OPTION_LEVEL,
  OPTION_OFFSET,
  OPTION_PASSWORD,
  OPTION_PASS_THROUGH,
  OPTION_PREVENT_CLOSE,
  OPTION_RAW_PASSWORD,
  OPTION_SIGNAL,
  OPTION_SUPPORT_ZIP64_SPLIT_FILE,
  OPTION_TRANSFER_STREAMS,
  OPTION_UNIX_EXTRA_FIELD_TYPE,
  OPTION_USDZ,
  OPTION_USE_UNICODE_FILE_NAMES
};
